// <auto-generated />
namespace Cleverbit.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_auditable_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_auditable_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "202104260710017_added_auditable_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
